name: vantablack_hub
description: "Vantablack Hub by KAI IA - Matriz de variantes cognitivas locales."
publish_to: 'none'
version: 2.0.0+13

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.4.0
  path_provider: ^2.1.0
  uuid: ^4.3.3
  open_file: ^3.3.2
  google_mlkit_translation: ^0.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  # REGISTRO DEL LOGO DE NEÓN GLOBAL
  assets:
    - assets/logo.png