name: vantablack_hub
description: "Vantablack Hub by KAI IA - Matriz de variantes cognitivas locales."
publish_to: 'none'
version: 3.0.0+40

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.4.0
  path_provider: ^2.1.0
  uuid: ^4.3.3
  open_file: ^3.3.2
  llama_flutter_android: ^0.2.0
  flutter_tts: ^4.0.2
  speech_to_text: ^7.0.0
  permission_handler: ^11.3.1
  shared_preferences: ^2.2.2
  file_picker: ^8.0.0
  image_picker: ^1.1.2
  syncfusion_flutter_pdf: ^34.1.33
  google_mlkit_text_recognition: ^0.16.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/logo.png"
  min_sdk_android: 26

flutter:
  uses-material-design: true
  
  # REGISTRO DEL LOGO Y ASSETS DE VOZ / LIVE MODE
  assets:
    - assets/logo.png
    - assets/kai_image.jpg
    - assets/images/
    - assets/sounds/
    