name: vantablack_hub
description: "Vantablack Hub by KAI IA - Matriz de variantes cognitivas locales."
publish_to: 'none'
version: 2.3.5+23

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.4.0
  path_provider: ^2.1.0
  uuid: ^4.3.3
  open_file: ^3.3.2
  llama_flutter_android: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/logo.png"
  min_sdk_android: 26

flutter:
  uses-material-design: true
  
  # REGISTRO DEL LOGO DE NEÓN GLOBAL
  assets:
    - assets/logo.png