name: Build and Release Windows

on:
  push:
    branches: [ main ]

jobs:
  build-windows:
    runs-on: windows-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4

    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.22.x'
        channel: 'stable'

    - name: Install Dependencies
      run: flutter pub get

    - name: Enable Windows Desktop
      run: flutter config --enable-windows-desktop

    - name: Build Windows Executable
      run: flutter build windows --release

    - name: Compress Build Bundle
      run: |
        Compress-Archive -Path build\windows\x64\runner\Release\* -DestinationPath vantablack_hub_windows.zip -Force

    - name: Create Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "vantablack_hub_windows.zip"
        tag: "v3.1.0"
        name: "Vantablack Hub v3.1.0 (Windows)"
        allowUpdates: true
        token: ${{ secrets.GITHUB_TOKEN }}
