name: Build Windows Release

on:
  push:
    branches: [ main ]

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '17'

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.22.x'
        channel: 'stable'

    - name: Install Dependencies
      run: flutter pub get

    - name: Enable Windows Desktop
      run: flutter config --enable-windows-desktop

    - name: Build Windows Executable
      run: flutter build windows --release

    - name: Compress Build Bundle
      run: |
        Compress-Archive -Path build\windows\x64\runner\Release\* -DestinationPath vantablack_hub_windows.zip -Force
        Copy-Item -Path vantablack_hub_windows.zip -Destination docs\vantablack_hub_windows.zip -Force

    - name: Commit and Push Compiled Zip
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add vantablack_hub_windows.zip docs/vantablack_hub_windows.zip
        git commit -m "Fix(Release): Generado vantablack_hub_windows.zip en la raíz" || exit 0
        git push
